# Futurex
#[provider.p11hsm]
##env_module = "FXPKCS11_MODULE" # optional
#module = "/Users/johnz/futurex/fxpkcs11-mac-arm-4.59-8551/libfxpkcs11.dylib"
#env_cfg = "FXPKCS11_CFG"
#cfg = "/Users/johnz/futurex/fxpkcs11-mac-arm-4.59-8551/fxpkcs11.cfg"
#token_label = "Slot Token 0"
#user_pin = "safest"

## SoftHSM
[provider.p11hsm]
##env_module = "PKCS11_SOFTHSM2_MODULE" # optional
module = "/usr/local/lib/softhsm/libsofthsm2.so"
env_cfg = "SOFTHSM2_CONF"
cfg = "/etc/softhsm2.conf"
token_label = "Slot Token 0"
user_pin = "5678"
