[echo]
echo = "ping"

## Futurex
#[provider.p11hsm]
##env_module = "FXPKCS11_MODULE" # optional
#module = "/Users/johnz/futurex/fxpkcs11-mac-arm-4.59-8551/libfxpkcs11.dylib"
#env_cfg = "FXPKCS11_CFG"
#cfg = "/Users/johnz/futurex/fxpkcs11-mac-arm-4.59-8551/fxpkcs11.cfg"
#token_label = "Slot Token 0"
#user_pin = "safest"
#key_type = "account"
#key_label = "Slot Token 0/wfdc2/owner/1"

## SoftHSM
[provider.p11hsm]
##env_module = "PKCS11_SOFTHSM2_MODULE" # optional
module = "/usr/local/lib/softhsm/libsofthsm2.so"
env_cfg = "SOFTHSM2_CONF"
cfg = "/etc/softhsm2.conf"
token_label = "Slot Token 0"
user_pin = "5678"
key_type = "account"
key_label = "Slot Token 0/wfdc2/owner/1"

[chain_node]
grpc = "http://0.0.0.0:9090"  # tokenfactory
#grpc = "http://0.0.0.0:10292" # wfchain-1
prefix = "wf"
gas_denom = "stake"
gas_price = "0.00120"
gas_adjustment = "2.0"
tx_poll_interval = 100
tx_poll_timeout = 20000

tokenfactory_contract = "wf14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s2s4a5q"
aurum_contract = "wf1ghd753shjuwexxywmgs4xz7x2q732vcnkm6h2pyv9s6ah3hylvrqzgrrlr"
#tokenfactory_contract = "wf14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s2s4a5q"
#aurum_contract = "wf1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqx9slkx"

[wallet_server]
grpc = "127.0.0.1:8080"